INFO:root:Contract /../data/reentrancy/solidity_contract/27248.sol:SimpleMultiSig:
INFO:symExec:Running, please wait...
Traceback (most recent call last):

  File "_ctypes/callbacks.c", line 315, in 'calling callback function'
  .oooooo.             o8o            o8o          
  File "/root/osiris/z3/z3.py", line 137, in z3_error_handler
 d8P'  `Y8b            `"'            `"'          
888      888  .oooo.o oooo  oooo d8b oooo   .oooo.o
888      888 d88(  "8 `888  `888""8P `888  d88(  "8
888      888 `"Y88b.   888   888      888  `"Y88b. 
`88b    d88' o.  )88b  888   888      888  o.  )88b
 `Y8bood8P'  8""888P' o888o d888b    o888o 8""888P'


!!! SYMBOLIC EXECUTION TIMEOUT !!!
    def z3_error_handler(c, e):
  File "/root/osiris/symExec.py", line 2868, in handler
    raise Exception("timeout")
Exception: timeout
INFO:symExec:	============ Results ===========
INFO:symExec:	  EVM code coverage: 	 98.0%
INFO:symExec:	  Arithmetic bugs: 	 True
INFO:symExec:	  └> Overflow bugs: 	 True
/../data/reentrancy/solidity_contract/27248.sol:SimpleMultiSig:37:13
nonce + 1
^
INFO:symExec:	  └> Underflow bugs: 	 False
INFO:symExec:	  └> Division bugs: 	 False
INFO:symExec:	  └> Modulo bugs:   	 False
INFO:symExec:	  └> Truncation bugs: 	 False
INFO:symExec:	  └> Signedness bugs: 	 False
INFO:symExec:	  Callstack bug: 	 False
INFO:symExec:	  Concurrency bug: 	 False
INFO:symExec:	  Time dependency bug: 	 False
INFO:symExec:	  Reentrancy bug: 	 True
/../data/reentrancy/solidity_contract/27248.sol:SimpleMultiSig:38:13
destination.call.value(value)(data)
^
INFO:symExec:	 --- 49.9913070202 seconds ---
INFO:symExec:	====== Analysis Completed ======